import { DASHBOARDS_PREFIX_PATH } from '@/constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import { ADMIN, USER } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const dashboardsNavigationConfig: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '',
        title: 'داشبورد',
        translateKey: '',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        meta: {
            horizontalMenu: {
                layout: 'default',
            },
        },
        subMenu: [ 
            {
                key: 'concepts.Dashboard',
                path: '/concepts/Dashboard',
                title: 'داشبورد',
                translateKey: 'nav.dashboard',
                icon: 'graph',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
             {
                key: 'concepts.bots.botList',
                path: '/concepts/bots/bot-list',
                title: 'بات ها',
                translateKey: 'nav.dashboard.bots',
                icon: 'Robot',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },  
            {
                key: 'concepts.autoReply.list',
                path: '/concepts/auto-reply/list',
                title: 'پاسخ خودکار',
                translateKey: 'nav.dashboard.autoReply',
                icon: 'feedback',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'concepts.inbox',
                path: '/concepts/inbox',
                title: 'صندوق ورودی پیام‌ها',
                translateKey: 'nav.concepts.inbox',
                icon: 'chat',
                type: 'item',
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'concepts.Integrations',
                path: '/concepts/Integrations',
                title: 'اتصال به کانال',
                translateKey: 'nav.concepts.Integrations',
                icon: 'chat',
                type: 'item',
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'concepts.WidgetBuilder',
                path: '/concepts/WidgetBuilder',
                title: 'استودیوی گفتگو',
                translateKey: 'nav.concepts.WidgetBuilder',
                icon: 'chat',
                type: 'item',
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'concepts.CampaignBuilder',
                path: '/concepts/CampaignBuilder',
                title: 'ارسال گروهی',
                translateKey: 'nav.concepts.CampaignBuilder',
                icon: 'chat',
                type: 'item',
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'concepts.crm',
                path: '/concepts/Contacts',
                title: 'مخاطبین',
                translateKey: 'nav.concepts.Contacts',
                icon: 'chat',
                type: 'item',
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'concepts.aiConfig',
                path: '/concepts/ai-settings',
                title: 'تنظیمات هوش مصنوعی',
                translateKey: 'nav.concepts.ai-settings',
                icon: 'chat',
                type: 'item',
                authority: [ADMIN, USER],
                subMenu: [],
            },



            {
                key: 'dashboard.ecommerce',
                path: `${DASHBOARDS_PREFIX_PATH}/ecommerce`,
                title: 'تجارت الکترونیک',
                translateKey: 'nav.dashboard.ecommerce',
                icon: 'dashboardEcommerce',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'dashboard.project',
                path: `${DASHBOARDS_PREFIX_PATH}/project`,
                title: 'پروژه',
                translateKey: 'nav.dashboard.project',
                icon: 'dashboardProject',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'dashboard.marketing',
                path: `${DASHBOARDS_PREFIX_PATH}/marketing`,
                title: 'بازاریابی',
                translateKey: 'nav.dashboard.marketing',
                icon: 'dashboardMarketing',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'dashboard.analytic',
                path: `${DASHBOARDS_PREFIX_PATH}/analytic`,
                title: 'تحلیلی',
                translateKey: 'nav.dashboard.analytic',
                icon: 'dashboardAnalytic',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
        ],
    },
]


export default dashboardsNavigationConfig
